# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4b256bd348d3d5ad1b090fa2855b1bae2bdbefb5fcab763fbbdbc80be33f069c52945e259d138b02cdbceede672963f5f90a54244ebabbcb59aea22dbecf332c

test:
  secret_key_base: 9bd960c693a8adf703255f773044fe2b3b48abdf0581f6efa38fb4318682d72220319bb29402ee56d81986121629f0888d4bec2b2c840f72eabd0c42b36fb6ef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
